"use client";

import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { db, storage } from "@/lib/firebase/config";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";
import { getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { ArrowLeft, Upload, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import React, { useState } from "react";

export default function AddPersonPage() {
  const [name, setName] = useState("");
  const [relation, setRelation] = useState("");
  const [images, setImages] = useState<File[]>([]);
  const [previews, setPreviews] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      const files = Array.from(e.target.files);
      setImages((prev) => [...prev, ...files]);

      files.forEach((file) => {
        const reader = new FileReader();
        reader.onloadend = () => {
          setPreviews((prev) => [...prev, reader.result as string]);
        };
        reader.readAsDataURL(file);
      });
    }
  };

  const removeImage = (index: number) => {
    setImages((prev) => prev.filter((_, i) => i !== index));
    setPreviews((prev) => prev.filter((_, i) => i !== index));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name || images.length === 0) {
      alert("Please provide name and at least one image");
      return;
    }

    setLoading(true);
    try {
      // Upload images to Firebase Storage
      const imageUrls = await Promise.all(
        images.map(async (image, index) => {
          const imageName = `${Date.now()}_${index}_${image.name}`;
          const imageRef = ref(storage, `persons/${imageName}`);
          await uploadBytes(imageRef, image);
          return getDownloadURL(imageRef);
        })
      );

      // Add person to Firestore
      await addDoc(collection(db, "known_users"), {
        name,
        relation,
        trainingImages: imageUrls,
        embedding: [], // Will be generated by Cloud Function
        createdAt: serverTimestamp(),
        detectionCount: 0,
        lastSeen: null,
      });

      // Register with Python AI Backend
      try {
        await Promise.all(
          images.map(async (image) => {
            const formData = new FormData();
            formData.append("name", name);
            formData.append("image", image);

            const res = await fetch("http://localhost:5001/register", {
              method: "POST",
              body: formData,
            });
            
            if (!res.ok) {
                console.error(`Failed to register image with AI backend: ${res.statusText}`);
            }
          })
        );
      } catch (error) {
        console.error("Error registering with AI backend:", error);
        alert("Saved to database, but AI registration failed. Ensure backend is running.");
      }

      router.push("/dashboard/known-persons");
    } catch (error) {
      console.error("Error adding person:", error);
      alert("Failed to add person. Please try again.");
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      <div className="flex items-center gap-4">
        <Link href="/dashboard/known-persons">
          <Button variant="outline" size="sm">
            <ArrowLeft className="h-4 w-4" />
          </Button>
        </Link>
        <div>
          <h1 className="text-3xl font-bold text-white">Add New Person</h1>
          <p className="text-slate-400 mt-1">
            Register a new person for recognition
          </p>
        </div>
      </div>

      <Card className="p-8">
        <form onSubmit={handleSubmit} className="space-y-6">
          <Input
            label="Full Name"
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="John Doe"
            required
          />

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">
              Relation
            </label>
            <select
              value={relation}
              onChange={(e) => setRelation(e.target.value)}
              className="w-full px-4 py-3 bg-slate-900 border border-slate-700 rounded-lg text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select relation</option>
              <option value="father">Father</option>
              <option value="mother">Mother</option>
              <option value="son">Son</option>
              <option value="daughter">Daughter</option>
              <option value="sibling">Sibling</option>
              <option value="spouse">Spouse</option>
              <option value="friend">Friend</option>
              <option value="other">Other</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-slate-300 mb-2">
              Training Images{" "}
              <span className="text-slate-500">
                (Multiple images improve accuracy)
              </span>
            </label>

            <div className="border-2 border-dashed border-slate-700 rounded-lg p-8 text-center hover:border-blue-500 transition-colors">
              <Upload className="h-12 w-12 mx-auto text-slate-600 mb-4" />
              <p className="text-slate-400 mb-2">
                Click to upload or drag and drop
              </p>
              <p className="text-sm text-slate-500 mb-4">PNG, JPG up to 10MB</p>
              <input
                type="file"
                multiple
                accept="image/*"
                onChange={handleImageChange}
                className="hidden"
                id="image-upload"
              />
              <label htmlFor="image-upload">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() =>
                    document.getElementById("image-upload")?.click()
                  }
                >
                  Select Images
                </Button>
              </label>
            </div>

            {previews.length > 0 && (
              <div className="grid grid-cols-3 gap-4 mt-4">
                {previews.map((preview, index) => (
                  <div key={index} className="relative group">
                    <div className="relative h-32 rounded-lg overflow-hidden">
                      <Image
                        src={preview}
                        alt={`Preview ${index}`}
                        fill
                        className="object-cover"
                      />
                    </div>
                    <button
                      type="button"
                      onClick={() => removeImage(index)}
                      className="absolute top-2 right-2 p-1 bg-red-500 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <X className="h-4 w-4 text-white" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="flex gap-4">
            <Link href="/dashboard/known-persons" className="flex-1">
              <Button type="button" variant="outline" className="w-full">
                Cancel
              </Button>
            </Link>
            <Button
              type="submit"
              variant="primary"
              className="flex-1"
              isLoading={loading}
            >
              Add Person
            </Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
